### ISSUE TITLE
Documentación Eentrega2

### ISSUE THREAD

**Issue by crismonrub** [Arquisoft/Trivial4a#16]
Debido a que, por los motivos que fuesen, se han quedado bastantes cosas en el tintero en lo que se refiere a la documentación de la segunda entrega y se pueden ir modificando cada parte de las prácticas hasta que sean evaluadas al final del semestre, en los próximos días intentaré completarla para conseguir que sea lo más completa y fiel posible en relación a la implementación del juego. Por supuesto, hablaré con todos para consensuar en equipo qué cosas añadir (o quitar si es el caso). :)

**Comment by angelrodb** [comment]
He subido una versión inicial de diagrama BPMN, echadle un ojo y si veis que podemos poner más cosas para representar el desarrollo de una partida decidmelo

**Comment by crismonrub** [comment]
Por si acaso, le mandé un par de correos a uno de los profesores comentándole precisamente lo del tema de la documentación de la segunda entrega que reflejaba en esta issue. Ante la respuesta recibida, que venía a decir que no perdiésemos el tiempo intentando modificar la anterior y que nos centremos en la última, ya que se supone que mejorará las ya entregadas y es la que más cuenta. Por lo tanto cierro ya esta issue, que no me había dado cuenta de que no lo había hecho.
