### ISSUE TITLE
Error en configuracion de usuario

### ISSUE THREAD

**Issue by angelrodb** [Arquisoft/Trivial4a#2]
Tenía un problema en la configuración de git y todos los commit que hacía salía que los hacía un tal UO231477, si pregunta labra es un error mio, creo que ya está arreglado y funciona bien, es sólo para que sepáis que UO231477 no existe

**Comment by Migferf** [comment]
Tal vez un donante anónimo nos esté ayudando.

**Comment by ghost** [comment]
Recuerdalo para si lo pregunta. Dejo la Issue cerrada.
